No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
No paths_local.yml file found. Please copy paths.yml to paths_local.yml and edit with your local paths. Do not add the latter file to the git tree.
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
Traceback (most recent call last):
  File "/global/homes/e/eunseong/cmbhalolensing/stack.py", line 3, in <module>
    import utils as cutils
  File "/global/u1/e/eunseong/cmbhalolensing/utils.py", line 16, in <module>
    paths = bunch.Bunch(io.config_from_yaml("input/paths_local.yml"))
  File "/global/homes/e/eunseong/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/orphics/io.py", line 96, in config_from_yaml
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input/paths_local.yml'
srun: error: nid01571: task 13: Exited with exit code 1
srun: Terminating job step 38261220.0
srun: error: nid01458: tasks 4-5: Exited with exit code 1
srun: error: nid01570: tasks 10-11: Exited with exit code 1
srun: error: nid01457: tasks 2-3: Exited with exit code 1
srun: error: nid01572: tasks 14-15: Exited with exit code 1
srun: error: nid01459: tasks 6-7: Exited with exit code 1
srun: error: nid01191: tasks 0-1: Exited with exit code 1
srun: error: nid01569: tasks 8-9: Exited with exit code 1
srun: error: nid01571: task 12: Exited with exit code 1
